version: '3.1'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped

    ports:
      - "${NGINX_PORT:-8400}:85"

    env_file:
      - ./../.env

    volumes:
      - ./../nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - inventory_system_frontend

  inventory_system_frontend:
    container_name: inventory_system_frontend
    restart: unless-stopped
    build:
      context: ./../src/frontend
      dockerfile: Dockerfile

    volumes:
      - ./../src/frontend:/app

    env_file:
      - ./../.env

    command: npm start

    depends_on:
      - inventory_system_api

  inventory_system_api:
    container_name: inventory_system_api
    restart: unless-stopped
    ports:
      - 8500:8500
    build: 
      context: ./../src/backends
      dockerfile: Dockerfile

    volumes:
      - ./../src/backends:/usr/src/inventory_system_backends

    command: uvicorn main:app --reload --port 8500 --host 0.0.0.0

    env_file:
      - ./../.env

    depends_on:
      - inventory_db

  inventory_db:
    container_name: inventory_db
    image: postgres:latest
    restart: always
    volumes:
      - ./../msd_db_mount_location/:/var/lib/postgresql/data

    ports:
      - '5432:5432'

    env_file:
      - ./../.env

networks:
  default:
    external: true
    name: inventory_system_network